# Generated by Django 4.2.23 on 2025-08-14 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin système'), ('DIRECTION', 'Direction'), ('ENSEIGNANT', 'Enseignant'), ('SURVEILLANT', 'Surveillant'), ('COMPTABLE', 'Comptable'), ('PARENT', 'Parent'), ('ELEVE', 'Élève')], default='DIRECTION', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
