# Generated by Django 4.2.23 on 2025-08-20 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du cycle')),
                ('notation', models.PositiveIntegerField(default=20, verbose_name='Notation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to='catalog.school', verbose_name='École')),
            ],
            options={
                'ordering': ['school__name', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='cycle',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='uniq_cycle_per_school'),
        ),
    ]
