# Generated by Django 4.2.23 on 2025-08-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_cycle_cycle_uniq_cycle_per_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cycle',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='cycle',
            name='uniq_cycle_per_school',
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='school',
        ),
        migrations.AlterField(
            model_name='cycle',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='notation',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
