# Generated by Django 4.2.23 on 2025-08-21 17:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_cycle_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['label']},
        ),
        migrations.AlterModelOptions(
            name='cycle',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classroom',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='catalog.cycle'),
        ),
        migrations.AddField(
            model_name='cycle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classroom',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.grade'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='label',
            field=models.CharField(max_length=50, verbose_name='Nom de la classe'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom du cycle'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='notation',
            field=models.PositiveIntegerField(default=20, verbose_name='Notation'),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('school', 'label'), name='uniq_classroom_label_per_school'),
        ),
    ]
