# Generated by Django 4.2.23 on 2025-08-21 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0004_alter_classroom_options_alter_cycle_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['label'], 'verbose_name': 'Classe', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='cycle',
            options={'ordering': ['name'], 'verbose_name': 'Cycle', 'verbose_name_plural': 'Cycles'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['level', 'name']},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='schoolyear',
            options={'ordering': ['-is_active', '-start_date']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'Matière', 'verbose_name_plural': 'Matières'},
        ),
        migrations.RemoveConstraint(
            model_name='classroom',
            name='uniq_classroom_label_per_school',
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='catalog.cycle', verbose_name='Cycle'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='label',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='main_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_classes', to=settings.AUTH_USER_MODEL, verbose_name='Professeur principal'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='catalog.school'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='notation',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='grade',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='catalog.school'),
        ),
        migrations.AlterField(
            model_name='schoolyear',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_years', to='catalog.school'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='catalog.school'),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('school', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('school', 'name')},
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='grade',
        ),
    ]
