# Generated by Django 4.2.23 on 2025-08-22 20:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_classroom_options_alter_cycle_options_and_more"),
        ("students", "0001_initial"),
    ]

    operations = [
        # Options & tri par défaut
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["last_name", "first_name"]},
        ),

        # On peut garder l'unique_together tel quel pour l’instant, on le modifiera APRÈS
        # la suppression de `school` (voir plus bas).

        # Si le modèle Enrollment n'existe plus dans ton code, on drop sa table
        migrations.DeleteModel(
            name="Enrollment",
        ),

        # --- Renommages de champs sans changer les colonnes SQL ---
        migrations.RenameField(
            model_name="student",
            old_name="birthdate",
            new_name="birth_date",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="sex",
            new_name="gender",
        ),

        # On précise db_column pour réutiliser les colonnes existantes
        migrations.AlterField(
            model_name="student",
            name="birth_date",
            field=models.DateField(
                blank=True,
                null=True,
                db_column="birthdate",
                verbose_name="Date de naissance",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(
                max_length=1,
                blank=True,
                null=True,
                choices=[("M", "Masculin"), ("F", "Féminin")],
                db_column="sex",
                verbose_name="Genre",
            ),
        ),

        # --- Nouveaux champs ---
        migrations.AddField(
            model_name="student",
            name="city",
            field=models.CharField(
                max_length=100, blank=True, null=True, verbose_name="Ville"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="district",
            field=models.CharField(
                max_length=100, blank=True, null=True, verbose_name="Quartier"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="photo",
            field=models.ImageField(
                upload_to="students/", blank=True, null=True, verbose_name="Photo"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="classroom",
            field=models.ForeignKey(
                to="catalog.classroom",
                on_delete=django.db.models.deletion.SET_NULL,
                blank=True,
                null=True,
                verbose_name="Classe",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="enrollment_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date d'inscription"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="parent_name",
            field=models.CharField(
                max_length=150, blank=True, null=True, verbose_name="Nom du parent"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="parent_phone",
            field=models.CharField(
                max_length=50,
                blank=True,
                null=True,
                verbose_name="N° Téléphone du parent",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Observation"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),

        # Ajustements de champs existants
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="Prénom"),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="student",
            name="matricule",
            field=models.CharField(
                max_length=50, blank=True, null=True, verbose_name="Matricule"
            ),
        ),

        # --- IMPORTANT : on enlève d'abord le champ `school` ---
        # (Fais-le uniquement si tu l’as bien retiré du modèle Student)
        migrations.RemoveField(
            model_name="student",
            name="school",
        ),

        # --- ENSUITE on nettoie unique_together ---
        # À ce stade, `school` n’existe plus donc MySQL ne tentera pas
        # de créer l’index FK 'school' avant de drop l’unique composé.
        migrations.AlterUniqueTogether(
            name="student",
            unique_together=set(),
        ),
    ]
